#!/home/ai-hat-embedded/hailo-apps/venv_hailo_apps/bin/python3
import sys
from hailo_apps.python.pipeline_apps.paddle_ocr.paddle_ocr import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
